# Generated by Django 4.2.23 on 2025-08-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('ratings', models.FloatField(blank=True, null=True)),
                ('ideal_duration', models.FloatField(blank=True, null=True)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=100, null=True)),
                ('city_desc', models.TextField(blank=True, null=True)),
                ('destinationid', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('ratings_place', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('place_desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
