# Generated by Django 5.2.9 on 2026-01-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_aiinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='interests',
            field=models.TextField(blank=True, help_text='Comma-separated interests (e.g., hiking, museums, food)'),
        ),
        migrations.AddField(
            model_name='traveler',
            name='travel_style',
            field=models.CharField(blank=True, help_text='Travel style preference (e.g., budget, luxury, adventure)', max_length=100),
        ),
    ]
